//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace gcp.model
{
    public partial class Aluno
    {
        public int ID { get; set; }
        public int mid { get; set; }
        public string nome { get; set; }
        public string ano_letivo { get; set; }
        public string CFC { get; set; }
        public string BF { get; set; }
        public string designacao { get; set; }
        public string NIS { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> data_de_nascimento { get; set; }
        public string nacionalidade { get; set; }
        public string uf { get; set; }
        public string religiao { get; set; }
        public Nullable<bool> frequentou_EI { get; set; }
        public string pai { get; set; }
        public string pai_RG { get; set; }
        public Nullable<bool> pai_falecido { get; set; }
        public Nullable<int> pai_instrucao { get; set; }
        public Nullable<bool> pai_mora_com_aluno { get; set; }
        public string pai_profissao { get; set; }
        public string mae { get; set; }
        public string mae_NIS { get; set; }
        public string mae_RG { get; set; }
        public Nullable<bool> mae_falecida { get; set; }
        public Nullable<int> mae_instrucao { get; set; }
        public Nullable<bool> mae_mora_com_aluno { get; set; }
        public string mae_profissao { get; set; }
        public string responsavel { get; set; }
        public string responsavel_tipo { get; set; }
        public string responsavel_endereco { get; set; }
        public string responsavel_CEP { get; set; }
        public string responsavel_telefone { get; set; }
        public string contato_1 { get; set; }
        public string telefone_contato_1 { get; set; }
        public string contato_2 { get; set; }
        public string telefone_contato_2 { get; set; }
        public string problemas_de_saude { get; set; }
        public string educacao_especial { get; set; }
        public string atendimento_especial { get; set; }
        public string frequentou_outra_instituicao { get; set; }
        public string meio_de_transporte { get; set; }
        public string tempo_de_deslocamento { get; set; }
        public Nullable<System.DateTime> data_de_preenchimento { get; set; }
        public string responsavel_pelo_preenchimento { get; set; }
        public Nullable<int> turma_id { get; set; }
    
        public virtual Instrucao Instrucao { get; set; }
        public virtual Instrucao Instrucao1 { get; set; }
        public virtual Sexo Sexo1 { get; set; }
        public virtual Turma Turma { get; set; }
    }
    
}
