//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace gcp.model
{
    public partial class Instrucao
    {
        public Instrucao()
        {
            this.Aluno = new HashSet<Aluno>();
            this.Aluno1 = new HashSet<Aluno>();
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public string nome { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual ICollection<Aluno> Aluno1 { get; set; }
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
    
}
