//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace gcp.model
{
    public partial class dadoscp : DbContext
    {
        public dadoscp()
            : base("name=dadoscp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aluno> Aluno { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<Instrucao> Instrucao { get; set; }
        public DbSet<Professor> Professor { get; set; }
        public DbSet<Sexo> Sexo { get; set; }
        public DbSet<Turma> Turma { get; set; }
    }
}
