//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("model", "FK_Aluno_Instrucao", "Instrucao", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Instrucao), "Aluno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Aluno), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Aluno_InstrucaoMae", "Instrucao", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Instrucao), "Aluno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Aluno), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Aluno_Sexo", "Sexo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Sexo), "Aluno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Aluno), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Aluno_Turma", "Turma", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Turma), "Aluno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Aluno), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Funcionario_Instrucao", "Instrucao", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Instrucao), "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Funcionario), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Funcionario_Sexo", "Sexo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Sexo), "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Funcionario), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Professor_Funcionario", "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(gcp.Funcionario), "Professor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Professor), true)]
[assembly: EdmRelationshipAttribute("model", "FK_Turma_Professor", "Professor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(gcp.Professor), "Turma", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Turma), true)]
[assembly: EdmRelationshipAttribute("model", "Auxiliar", "Funcionario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(gcp.Funcionario), "Turma", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(gcp.Turma))]

#endregion

namespace gcp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dadoscp : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dadoscp object using the connection string found in the 'dadoscp' section of the application configuration file.
        /// </summary>
        public dadoscp() : base("name=dadoscp", "dadoscp")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dadoscp object.
        /// </summary>
        public dadoscp(string connectionString) : base(connectionString, "dadoscp")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dadoscp object.
        /// </summary>
        public dadoscp(EntityConnection connection) : base(connection, "dadoscp")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aluno> Aluno
        {
            get
            {
                if ((_Aluno == null))
                {
                    _Aluno = base.CreateObjectSet<Aluno>("Aluno");
                }
                return _Aluno;
            }
        }
        private ObjectSet<Aluno> _Aluno;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Funcionario> Funcionario
        {
            get
            {
                if ((_Funcionario == null))
                {
                    _Funcionario = base.CreateObjectSet<Funcionario>("Funcionario");
                }
                return _Funcionario;
            }
        }
        private ObjectSet<Funcionario> _Funcionario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Instrucao> Instrucao
        {
            get
            {
                if ((_Instrucao == null))
                {
                    _Instrucao = base.CreateObjectSet<Instrucao>("Instrucao");
                }
                return _Instrucao;
            }
        }
        private ObjectSet<Instrucao> _Instrucao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Professor> Professor
        {
            get
            {
                if ((_Professor == null))
                {
                    _Professor = base.CreateObjectSet<Professor>("Professor");
                }
                return _Professor;
            }
        }
        private ObjectSet<Professor> _Professor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sexo> Sexo
        {
            get
            {
                if ((_Sexo == null))
                {
                    _Sexo = base.CreateObjectSet<Sexo>("Sexo");
                }
                return _Sexo;
            }
        }
        private ObjectSet<Sexo> _Sexo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Turma> Turma
        {
            get
            {
                if ((_Turma == null))
                {
                    _Turma = base.CreateObjectSet<Turma>("Turma");
                }
                return _Turma;
            }
        }
        private ObjectSet<Turma> _Turma;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aluno EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAluno(Aluno aluno)
        {
            base.AddObject("Aluno", aluno);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Funcionario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFuncionario(Funcionario funcionario)
        {
            base.AddObject("Funcionario", funcionario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Instrucao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInstrucao(Instrucao instrucao)
        {
            base.AddObject("Instrucao", instrucao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Professor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfessor(Professor professor)
        {
            base.AddObject("Professor", professor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sexo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSexo(Sexo sexo)
        {
            base.AddObject("Sexo", sexo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Turma EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTurma(Turma turma)
        {
            base.AddObject("Turma", turma);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="model", Name="Aluno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aluno : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aluno object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="mid">Initial value of the mid property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        public static Aluno CreateAluno(global::System.Int32 id, global::System.Int32 mid, global::System.String nome)
        {
            Aluno aluno = new Aluno();
            aluno.ID = id;
            aluno.mid = mid;
            aluno.nome = nome;
            return aluno;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mid
        {
            get
            {
                return _mid;
            }
            set
            {
                OnmidChanging(value);
                ReportPropertyChanging("mid");
                _mid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mid");
                OnmidChanged();
            }
        }
        private global::System.Int32 _mid;
        partial void OnmidChanging(global::System.Int32 value);
        partial void OnmidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ano_letivo
        {
            get
            {
                return _ano_letivo;
            }
            set
            {
                Onano_letivoChanging(value);
                ReportPropertyChanging("ano_letivo");
                _ano_letivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ano_letivo");
                Onano_letivoChanged();
            }
        }
        private global::System.String _ano_letivo;
        partial void Onano_letivoChanging(global::System.String value);
        partial void Onano_letivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CFC
        {
            get
            {
                return _CFC;
            }
            set
            {
                OnCFCChanging(value);
                ReportPropertyChanging("CFC");
                _CFC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CFC");
                OnCFCChanged();
            }
        }
        private global::System.String _CFC;
        partial void OnCFCChanging(global::System.String value);
        partial void OnCFCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BF
        {
            get
            {
                return _BF;
            }
            set
            {
                OnBFChanging(value);
                ReportPropertyChanging("BF");
                _BF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BF");
                OnBFChanged();
            }
        }
        private global::System.String _BF;
        partial void OnBFChanging(global::System.String value);
        partial void OnBFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String designacao
        {
            get
            {
                return _designacao;
            }
            set
            {
                OndesignacaoChanging(value);
                ReportPropertyChanging("designacao");
                _designacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("designacao");
                OndesignacaoChanged();
            }
        }
        private global::System.String _designacao;
        partial void OndesignacaoChanging(global::System.String value);
        partial void OndesignacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NIS
        {
            get
            {
                return _NIS;
            }
            set
            {
                OnNISChanging(value);
                ReportPropertyChanging("NIS");
                _NIS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NIS");
                OnNISChanged();
            }
        }
        private global::System.String _NIS;
        partial void OnNISChanging(global::System.String value);
        partial void OnNISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_de_nascimento
        {
            get
            {
                return _data_de_nascimento;
            }
            set
            {
                Ondata_de_nascimentoChanging(value);
                ReportPropertyChanging("data_de_nascimento");
                _data_de_nascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_de_nascimento");
                Ondata_de_nascimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_de_nascimento;
        partial void Ondata_de_nascimentoChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_de_nascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nacionalidade
        {
            get
            {
                return _nacionalidade;
            }
            set
            {
                OnnacionalidadeChanging(value);
                ReportPropertyChanging("nacionalidade");
                _nacionalidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nacionalidade");
                OnnacionalidadeChanged();
            }
        }
        private global::System.String _nacionalidade;
        partial void OnnacionalidadeChanging(global::System.String value);
        partial void OnnacionalidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String uf
        {
            get
            {
                return _uf;
            }
            set
            {
                OnufChanging(value);
                ReportPropertyChanging("uf");
                _uf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("uf");
                OnufChanged();
            }
        }
        private global::System.String _uf;
        partial void OnufChanging(global::System.String value);
        partial void OnufChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String religiao
        {
            get
            {
                return _religiao;
            }
            set
            {
                OnreligiaoChanging(value);
                ReportPropertyChanging("religiao");
                _religiao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("religiao");
                OnreligiaoChanged();
            }
        }
        private global::System.String _religiao;
        partial void OnreligiaoChanging(global::System.String value);
        partial void OnreligiaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> frequentou_EI
        {
            get
            {
                return _frequentou_EI;
            }
            set
            {
                Onfrequentou_EIChanging(value);
                ReportPropertyChanging("frequentou_EI");
                _frequentou_EI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("frequentou_EI");
                Onfrequentou_EIChanged();
            }
        }
        private Nullable<global::System.Boolean> _frequentou_EI;
        partial void Onfrequentou_EIChanging(Nullable<global::System.Boolean> value);
        partial void Onfrequentou_EIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pai
        {
            get
            {
                return _pai;
            }
            set
            {
                OnpaiChanging(value);
                ReportPropertyChanging("pai");
                _pai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pai");
                OnpaiChanged();
            }
        }
        private global::System.String _pai;
        partial void OnpaiChanging(global::System.String value);
        partial void OnpaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pai_RG
        {
            get
            {
                return _pai_RG;
            }
            set
            {
                Onpai_RGChanging(value);
                ReportPropertyChanging("pai_RG");
                _pai_RG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pai_RG");
                Onpai_RGChanged();
            }
        }
        private global::System.String _pai_RG;
        partial void Onpai_RGChanging(global::System.String value);
        partial void Onpai_RGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> pai_falecido
        {
            get
            {
                return _pai_falecido;
            }
            set
            {
                Onpai_falecidoChanging(value);
                ReportPropertyChanging("pai_falecido");
                _pai_falecido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pai_falecido");
                Onpai_falecidoChanged();
            }
        }
        private Nullable<global::System.Boolean> _pai_falecido;
        partial void Onpai_falecidoChanging(Nullable<global::System.Boolean> value);
        partial void Onpai_falecidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pai_instrucao
        {
            get
            {
                return _pai_instrucao;
            }
            set
            {
                Onpai_instrucaoChanging(value);
                ReportPropertyChanging("pai_instrucao");
                _pai_instrucao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pai_instrucao");
                Onpai_instrucaoChanged();
            }
        }
        private Nullable<global::System.Int32> _pai_instrucao;
        partial void Onpai_instrucaoChanging(Nullable<global::System.Int32> value);
        partial void Onpai_instrucaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> pai_mora_com_aluno
        {
            get
            {
                return _pai_mora_com_aluno;
            }
            set
            {
                Onpai_mora_com_alunoChanging(value);
                ReportPropertyChanging("pai_mora_com_aluno");
                _pai_mora_com_aluno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pai_mora_com_aluno");
                Onpai_mora_com_alunoChanged();
            }
        }
        private Nullable<global::System.Boolean> _pai_mora_com_aluno;
        partial void Onpai_mora_com_alunoChanging(Nullable<global::System.Boolean> value);
        partial void Onpai_mora_com_alunoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pai_profissao
        {
            get
            {
                return _pai_profissao;
            }
            set
            {
                Onpai_profissaoChanging(value);
                ReportPropertyChanging("pai_profissao");
                _pai_profissao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pai_profissao");
                Onpai_profissaoChanged();
            }
        }
        private global::System.String _pai_profissao;
        partial void Onpai_profissaoChanging(global::System.String value);
        partial void Onpai_profissaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mae
        {
            get
            {
                return _mae;
            }
            set
            {
                OnmaeChanging(value);
                ReportPropertyChanging("mae");
                _mae = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mae");
                OnmaeChanged();
            }
        }
        private global::System.String _mae;
        partial void OnmaeChanging(global::System.String value);
        partial void OnmaeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mae_NIS
        {
            get
            {
                return _mae_NIS;
            }
            set
            {
                Onmae_NISChanging(value);
                ReportPropertyChanging("mae_NIS");
                _mae_NIS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mae_NIS");
                Onmae_NISChanged();
            }
        }
        private global::System.String _mae_NIS;
        partial void Onmae_NISChanging(global::System.String value);
        partial void Onmae_NISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mae_RG
        {
            get
            {
                return _mae_RG;
            }
            set
            {
                Onmae_RGChanging(value);
                ReportPropertyChanging("mae_RG");
                _mae_RG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mae_RG");
                Onmae_RGChanged();
            }
        }
        private global::System.String _mae_RG;
        partial void Onmae_RGChanging(global::System.String value);
        partial void Onmae_RGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> mae_falecida
        {
            get
            {
                return _mae_falecida;
            }
            set
            {
                Onmae_falecidaChanging(value);
                ReportPropertyChanging("mae_falecida");
                _mae_falecida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mae_falecida");
                Onmae_falecidaChanged();
            }
        }
        private Nullable<global::System.Boolean> _mae_falecida;
        partial void Onmae_falecidaChanging(Nullable<global::System.Boolean> value);
        partial void Onmae_falecidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mae_instrucao
        {
            get
            {
                return _mae_instrucao;
            }
            set
            {
                Onmae_instrucaoChanging(value);
                ReportPropertyChanging("mae_instrucao");
                _mae_instrucao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mae_instrucao");
                Onmae_instrucaoChanged();
            }
        }
        private Nullable<global::System.Int32> _mae_instrucao;
        partial void Onmae_instrucaoChanging(Nullable<global::System.Int32> value);
        partial void Onmae_instrucaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> mae_mora_com_aluno
        {
            get
            {
                return _mae_mora_com_aluno;
            }
            set
            {
                Onmae_mora_com_alunoChanging(value);
                ReportPropertyChanging("mae_mora_com_aluno");
                _mae_mora_com_aluno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mae_mora_com_aluno");
                Onmae_mora_com_alunoChanged();
            }
        }
        private Nullable<global::System.Boolean> _mae_mora_com_aluno;
        partial void Onmae_mora_com_alunoChanging(Nullable<global::System.Boolean> value);
        partial void Onmae_mora_com_alunoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mae_profissao
        {
            get
            {
                return _mae_profissao;
            }
            set
            {
                Onmae_profissaoChanging(value);
                ReportPropertyChanging("mae_profissao");
                _mae_profissao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mae_profissao");
                Onmae_profissaoChanged();
            }
        }
        private global::System.String _mae_profissao;
        partial void Onmae_profissaoChanging(global::System.String value);
        partial void Onmae_profissaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String responsavel
        {
            get
            {
                return _responsavel;
            }
            set
            {
                OnresponsavelChanging(value);
                ReportPropertyChanging("responsavel");
                _responsavel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("responsavel");
                OnresponsavelChanged();
            }
        }
        private global::System.String _responsavel;
        partial void OnresponsavelChanging(global::System.String value);
        partial void OnresponsavelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String responsavel_tipo
        {
            get
            {
                return _responsavel_tipo;
            }
            set
            {
                Onresponsavel_tipoChanging(value);
                ReportPropertyChanging("responsavel_tipo");
                _responsavel_tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("responsavel_tipo");
                Onresponsavel_tipoChanged();
            }
        }
        private global::System.String _responsavel_tipo;
        partial void Onresponsavel_tipoChanging(global::System.String value);
        partial void Onresponsavel_tipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String responsavel_endereco
        {
            get
            {
                return _responsavel_endereco;
            }
            set
            {
                Onresponsavel_enderecoChanging(value);
                ReportPropertyChanging("responsavel_endereco");
                _responsavel_endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("responsavel_endereco");
                Onresponsavel_enderecoChanged();
            }
        }
        private global::System.String _responsavel_endereco;
        partial void Onresponsavel_enderecoChanging(global::System.String value);
        partial void Onresponsavel_enderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String responsavel_CEP
        {
            get
            {
                return _responsavel_CEP;
            }
            set
            {
                Onresponsavel_CEPChanging(value);
                ReportPropertyChanging("responsavel_CEP");
                _responsavel_CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("responsavel_CEP");
                Onresponsavel_CEPChanged();
            }
        }
        private global::System.String _responsavel_CEP;
        partial void Onresponsavel_CEPChanging(global::System.String value);
        partial void Onresponsavel_CEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String responsavel_telefone
        {
            get
            {
                return _responsavel_telefone;
            }
            set
            {
                Onresponsavel_telefoneChanging(value);
                ReportPropertyChanging("responsavel_telefone");
                _responsavel_telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("responsavel_telefone");
                Onresponsavel_telefoneChanged();
            }
        }
        private global::System.String _responsavel_telefone;
        partial void Onresponsavel_telefoneChanging(global::System.String value);
        partial void Onresponsavel_telefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contato_1
        {
            get
            {
                return _contato_1;
            }
            set
            {
                Oncontato_1Changing(value);
                ReportPropertyChanging("contato_1");
                _contato_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contato_1");
                Oncontato_1Changed();
            }
        }
        private global::System.String _contato_1;
        partial void Oncontato_1Changing(global::System.String value);
        partial void Oncontato_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone_contato_1
        {
            get
            {
                return _telefone_contato_1;
            }
            set
            {
                Ontelefone_contato_1Changing(value);
                ReportPropertyChanging("telefone_contato_1");
                _telefone_contato_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone_contato_1");
                Ontelefone_contato_1Changed();
            }
        }
        private global::System.String _telefone_contato_1;
        partial void Ontelefone_contato_1Changing(global::System.String value);
        partial void Ontelefone_contato_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contato_2
        {
            get
            {
                return _contato_2;
            }
            set
            {
                Oncontato_2Changing(value);
                ReportPropertyChanging("contato_2");
                _contato_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contato_2");
                Oncontato_2Changed();
            }
        }
        private global::System.String _contato_2;
        partial void Oncontato_2Changing(global::System.String value);
        partial void Oncontato_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone_contato_2
        {
            get
            {
                return _telefone_contato_2;
            }
            set
            {
                Ontelefone_contato_2Changing(value);
                ReportPropertyChanging("telefone_contato_2");
                _telefone_contato_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone_contato_2");
                Ontelefone_contato_2Changed();
            }
        }
        private global::System.String _telefone_contato_2;
        partial void Ontelefone_contato_2Changing(global::System.String value);
        partial void Ontelefone_contato_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String problemas_de_saude
        {
            get
            {
                return _problemas_de_saude;
            }
            set
            {
                Onproblemas_de_saudeChanging(value);
                ReportPropertyChanging("problemas_de_saude");
                _problemas_de_saude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("problemas_de_saude");
                Onproblemas_de_saudeChanged();
            }
        }
        private global::System.String _problemas_de_saude;
        partial void Onproblemas_de_saudeChanging(global::System.String value);
        partial void Onproblemas_de_saudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String educacao_especial
        {
            get
            {
                return _educacao_especial;
            }
            set
            {
                Oneducacao_especialChanging(value);
                ReportPropertyChanging("educacao_especial");
                _educacao_especial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("educacao_especial");
                Oneducacao_especialChanged();
            }
        }
        private global::System.String _educacao_especial;
        partial void Oneducacao_especialChanging(global::System.String value);
        partial void Oneducacao_especialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String atendimento_especial
        {
            get
            {
                return _atendimento_especial;
            }
            set
            {
                Onatendimento_especialChanging(value);
                ReportPropertyChanging("atendimento_especial");
                _atendimento_especial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("atendimento_especial");
                Onatendimento_especialChanged();
            }
        }
        private global::System.String _atendimento_especial;
        partial void Onatendimento_especialChanging(global::System.String value);
        partial void Onatendimento_especialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String frequentou_outra_instituicao
        {
            get
            {
                return _frequentou_outra_instituicao;
            }
            set
            {
                Onfrequentou_outra_instituicaoChanging(value);
                ReportPropertyChanging("frequentou_outra_instituicao");
                _frequentou_outra_instituicao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("frequentou_outra_instituicao");
                Onfrequentou_outra_instituicaoChanged();
            }
        }
        private global::System.String _frequentou_outra_instituicao;
        partial void Onfrequentou_outra_instituicaoChanging(global::System.String value);
        partial void Onfrequentou_outra_instituicaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meio_de_transporte
        {
            get
            {
                return _meio_de_transporte;
            }
            set
            {
                Onmeio_de_transporteChanging(value);
                ReportPropertyChanging("meio_de_transporte");
                _meio_de_transporte = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("meio_de_transporte");
                Onmeio_de_transporteChanged();
            }
        }
        private global::System.String _meio_de_transporte;
        partial void Onmeio_de_transporteChanging(global::System.String value);
        partial void Onmeio_de_transporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tempo_de_deslocamento
        {
            get
            {
                return _tempo_de_deslocamento;
            }
            set
            {
                Ontempo_de_deslocamentoChanging(value);
                ReportPropertyChanging("tempo_de_deslocamento");
                _tempo_de_deslocamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tempo_de_deslocamento");
                Ontempo_de_deslocamentoChanged();
            }
        }
        private global::System.String _tempo_de_deslocamento;
        partial void Ontempo_de_deslocamentoChanging(global::System.String value);
        partial void Ontempo_de_deslocamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_de_preenchimento
        {
            get
            {
                return _data_de_preenchimento;
            }
            set
            {
                Ondata_de_preenchimentoChanging(value);
                ReportPropertyChanging("data_de_preenchimento");
                _data_de_preenchimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_de_preenchimento");
                Ondata_de_preenchimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_de_preenchimento;
        partial void Ondata_de_preenchimentoChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_de_preenchimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String responsavel_pelo_preenchimento
        {
            get
            {
                return _responsavel_pelo_preenchimento;
            }
            set
            {
                Onresponsavel_pelo_preenchimentoChanging(value);
                ReportPropertyChanging("responsavel_pelo_preenchimento");
                _responsavel_pelo_preenchimento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("responsavel_pelo_preenchimento");
                Onresponsavel_pelo_preenchimentoChanged();
            }
        }
        private global::System.String _responsavel_pelo_preenchimento;
        partial void Onresponsavel_pelo_preenchimentoChanging(global::System.String value);
        partial void Onresponsavel_pelo_preenchimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> turma_id
        {
            get
            {
                return _turma_id;
            }
            set
            {
                Onturma_idChanging(value);
                ReportPropertyChanging("turma_id");
                _turma_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("turma_id");
                Onturma_idChanged();
            }
        }
        private Nullable<global::System.Int32> _turma_id;
        partial void Onturma_idChanging(Nullable<global::System.Int32> value);
        partial void Onturma_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_Instrucao", "Instrucao")]
        public Instrucao Instrucao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Aluno_Instrucao", "Instrucao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Aluno_Instrucao", "Instrucao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Instrucao> InstrucaoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Aluno_Instrucao", "Instrucao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Instrucao>("model.FK_Aluno_Instrucao", "Instrucao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_InstrucaoMae", "Instrucao")]
        public Instrucao Instrucao1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Aluno_InstrucaoMae", "Instrucao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Aluno_InstrucaoMae", "Instrucao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Instrucao> Instrucao1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Aluno_InstrucaoMae", "Instrucao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Instrucao>("model.FK_Aluno_InstrucaoMae", "Instrucao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_Sexo", "Sexo")]
        public Sexo Sexo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexo>("model.FK_Aluno_Sexo", "Sexo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexo>("model.FK_Aluno_Sexo", "Sexo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sexo> Sexo1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexo>("model.FK_Aluno_Sexo", "Sexo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sexo>("model.FK_Aluno_Sexo", "Sexo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_Turma", "Turma")]
        public Turma Turma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turma>("model.FK_Aluno_Turma", "Turma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turma>("model.FK_Aluno_Turma", "Turma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Turma> TurmaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turma>("model.FK_Aluno_Turma", "Turma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Turma>("model.FK_Aluno_Turma", "Turma", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="model", Name="Funcionario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Funcionario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Funcionario object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Funcionario CreateFuncionario(global::System.Int32 id)
        {
            Funcionario funcionario = new Funcionario();
            funcionario.id = id;
            return funcionario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_ingresso
        {
            get
            {
                return _data_ingresso;
            }
            set
            {
                Ondata_ingressoChanging(value);
                ReportPropertyChanging("data_ingresso");
                _data_ingresso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_ingresso");
                Ondata_ingressoChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_ingresso;
        partial void Ondata_ingressoChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_ingressoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_nascimento
        {
            get
            {
                return _data_nascimento;
            }
            set
            {
                Ondata_nascimentoChanging(value);
                ReportPropertyChanging("data_nascimento");
                _data_nascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_nascimento");
                Ondata_nascimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_nascimento;
        partial void Ondata_nascimentoChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_nascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RG
        {
            get
            {
                return _RG;
            }
            set
            {
                OnRGChanging(value);
                ReportPropertyChanging("RG");
                _RG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RG");
                OnRGChanged();
            }
        }
        private global::System.String _RG;
        partial void OnRGChanging(global::System.String value);
        partial void OnRGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String carteira_de_trabalho
        {
            get
            {
                return _carteira_de_trabalho;
            }
            set
            {
                Oncarteira_de_trabalhoChanging(value);
                ReportPropertyChanging("carteira_de_trabalho");
                _carteira_de_trabalho = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("carteira_de_trabalho");
                Oncarteira_de_trabalhoChanged();
            }
        }
        private global::System.String _carteira_de_trabalho;
        partial void Oncarteira_de_trabalhoChanging(global::System.String value);
        partial void Oncarteira_de_trabalhoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> instrucao
        {
            get
            {
                return _instrucao;
            }
            set
            {
                OninstrucaoChanging(value);
                ReportPropertyChanging("instrucao");
                _instrucao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("instrucao");
                OninstrucaoChanged();
            }
        }
        private Nullable<global::System.Int32> _instrucao;
        partial void OninstrucaoChanging(Nullable<global::System.Int32> value);
        partial void OninstrucaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Funcionario_Instrucao", "Instrucao")]
        public Instrucao Instrucao1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Funcionario_Instrucao", "Instrucao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Funcionario_Instrucao", "Instrucao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Instrucao> Instrucao1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Instrucao>("model.FK_Funcionario_Instrucao", "Instrucao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Instrucao>("model.FK_Funcionario_Instrucao", "Instrucao", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Funcionario_Sexo", "Sexo")]
        public Sexo Sexo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexo>("model.FK_Funcionario_Sexo", "Sexo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexo>("model.FK_Funcionario_Sexo", "Sexo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sexo> Sexo1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sexo>("model.FK_Funcionario_Sexo", "Sexo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sexo>("model.FK_Funcionario_Sexo", "Sexo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Professor_Funcionario", "Professor")]
        public Professor Professor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Professor>("model.FK_Professor_Funcionario", "Professor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Professor>("model.FK_Professor_Funcionario", "Professor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Professor> ProfessorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Professor>("model.FK_Professor_Funcionario", "Professor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Professor>("model.FK_Professor_Funcionario", "Professor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "Auxiliar", "Turma")]
        public Turma Turma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turma>("model.Auxiliar", "Turma").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turma>("model.Auxiliar", "Turma").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Turma> TurmaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Turma>("model.Auxiliar", "Turma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Turma>("model.Auxiliar", "Turma", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="model", Name="Instrucao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Instrucao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Instrucao object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Instrucao CreateInstrucao(global::System.Int32 id)
        {
            Instrucao instrucao = new Instrucao();
            instrucao.id = id;
            return instrucao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_Instrucao", "Aluno")]
        public EntityCollection<Aluno> Aluno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aluno>("model.FK_Aluno_Instrucao", "Aluno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aluno>("model.FK_Aluno_Instrucao", "Aluno", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_InstrucaoMae", "Aluno")]
        public EntityCollection<Aluno> Aluno1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aluno>("model.FK_Aluno_InstrucaoMae", "Aluno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aluno>("model.FK_Aluno_InstrucaoMae", "Aluno", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Funcionario_Instrucao", "Funcionario")]
        public EntityCollection<Funcionario> Funcionario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Funcionario>("model.FK_Funcionario_Instrucao", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Funcionario>("model.FK_Funcionario_Instrucao", "Funcionario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="model", Name="Professor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Professor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Professor object.
        /// </summary>
        /// <param name="id_funcionario">Initial value of the id_funcionario property.</param>
        /// <param name="id_turma">Initial value of the id_turma property.</param>
        public static Professor CreateProfessor(global::System.Int32 id_funcionario, global::System.Int32 id_turma)
        {
            Professor professor = new Professor();
            professor.id_funcionario = id_funcionario;
            professor.id_turma = id_turma;
            return professor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_funcionario
        {
            get
            {
                return _id_funcionario;
            }
            set
            {
                if (_id_funcionario != value)
                {
                    Onid_funcionarioChanging(value);
                    ReportPropertyChanging("id_funcionario");
                    _id_funcionario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_funcionario");
                    Onid_funcionarioChanged();
                }
            }
        }
        private global::System.Int32 _id_funcionario;
        partial void Onid_funcionarioChanging(global::System.Int32 value);
        partial void Onid_funcionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_turma
        {
            get
            {
                return _id_turma;
            }
            set
            {
                Onid_turmaChanging(value);
                ReportPropertyChanging("id_turma");
                _id_turma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_turma");
                Onid_turmaChanged();
            }
        }
        private global::System.Int32 _id_turma;
        partial void Onid_turmaChanging(global::System.Int32 value);
        partial void Onid_turmaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Professor_Funcionario", "Funcionario")]
        public Funcionario Funcionario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Funcionario>("model.FK_Professor_Funcionario", "Funcionario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Funcionario>("model.FK_Professor_Funcionario", "Funcionario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Funcionario> FuncionarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Funcionario>("model.FK_Professor_Funcionario", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Funcionario>("model.FK_Professor_Funcionario", "Funcionario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Turma_Professor", "Turma")]
        public EntityCollection<Turma> Turma
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Turma>("model.FK_Turma_Professor", "Turma");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Turma>("model.FK_Turma_Professor", "Turma", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="model", Name="Sexo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sexo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sexo object.
        /// </summary>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="abreviacao">Initial value of the abreviacao property.</param>
        public static Sexo CreateSexo(global::System.String nome, global::System.String abreviacao)
        {
            Sexo sexo = new Sexo();
            sexo.nome = nome;
            sexo.abreviacao = abreviacao;
            return sexo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String abreviacao
        {
            get
            {
                return _abreviacao;
            }
            set
            {
                if (_abreviacao != value)
                {
                    OnabreviacaoChanging(value);
                    ReportPropertyChanging("abreviacao");
                    _abreviacao = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("abreviacao");
                    OnabreviacaoChanged();
                }
            }
        }
        private global::System.String _abreviacao;
        partial void OnabreviacaoChanging(global::System.String value);
        partial void OnabreviacaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_Sexo", "Aluno")]
        public EntityCollection<Aluno> Aluno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aluno>("model.FK_Aluno_Sexo", "Aluno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aluno>("model.FK_Aluno_Sexo", "Aluno", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Funcionario_Sexo", "Funcionario")]
        public EntityCollection<Funcionario> Funcionario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Funcionario>("model.FK_Funcionario_Sexo", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Funcionario>("model.FK_Funcionario_Sexo", "Funcionario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="model", Name="Turma")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Turma : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Turma object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="professor_id">Initial value of the professor_id property.</param>
        public static Turma CreateTurma(global::System.Int32 id, global::System.Int32 professor_id)
        {
            Turma turma = new Turma();
            turma.id = id;
            turma.professor_id = professor_id;
            return turma;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 professor_id
        {
            get
            {
                return _professor_id;
            }
            set
            {
                Onprofessor_idChanging(value);
                ReportPropertyChanging("professor_id");
                _professor_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("professor_id");
                Onprofessor_idChanged();
            }
        }
        private global::System.Int32 _professor_id;
        partial void Onprofessor_idChanging(global::System.Int32 value);
        partial void Onprofessor_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String grupamento
        {
            get
            {
                return _grupamento;
            }
            set
            {
                OngrupamentoChanging(value);
                ReportPropertyChanging("grupamento");
                _grupamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("grupamento");
                OngrupamentoChanged();
            }
        }
        private global::System.String _grupamento;
        partial void OngrupamentoChanging(global::System.String value);
        partial void OngrupamentoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Aluno_Turma", "Aluno")]
        public EntityCollection<Aluno> Aluno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aluno>("model.FK_Aluno_Turma", "Aluno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aluno>("model.FK_Aluno_Turma", "Aluno", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "FK_Turma_Professor", "Professor")]
        public Professor Professor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Professor>("model.FK_Turma_Professor", "Professor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Professor>("model.FK_Turma_Professor", "Professor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Professor> ProfessorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Professor>("model.FK_Turma_Professor", "Professor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Professor>("model.FK_Turma_Professor", "Professor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("model", "Auxiliar", "Funcionario")]
        public EntityCollection<Funcionario> Funcionario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Funcionario>("model.Auxiliar", "Funcionario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Funcionario>("model.Auxiliar", "Funcionario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
